// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { defineApp } from './core/defineApp'
export type { RuntimeConfig } from './core/defineApp'
// @umijs/renderer-*
export { createBrowserHistory, createHashHistory, createMemoryHistory, createSearchParams, generatePath, matchPath, matchRoutes, Navigate, NavLink, Outlet, resolvePath, useLocation, useMatch, useNavigate, useOutlet, useOutletContext, useParams, useResolvedPath, useRoutes, useSearchParams, Helmet, useAppData, useSelectedRoutes, useClientLoaderData, useServerLoaderData, renderClient, __getRoot, Link, useRouteData, __useFetcher, withRouter } from '/home/code/go-zero-antd-backend/web/node_modules/@umijs/renderer-react';
export type {  History } from '/home/code/go-zero-antd-backend/web/node_modules/@umijs/renderer-react'
// umi/client/client/plugin
export { ApplyPluginsType, PluginManager } from '/home/code/go-zero-antd-backend/web/node_modules/umi/client/client/plugin.js';
export { history, createHistory } from './core/history';
export { terminal } from './core/terminal';
export { TestBrowser } from './testBrowser';
// plugins
export { Access, useAccess, useAccessMarkedRoutes } from '/home/code/go-zero-antd-backend/web/src/.umi/plugin-access';
export { addLocale, setLocale, getLocale, getIntl, useIntl, injectIntl, formatMessage, FormattedMessage, getAllLocales, FormattedDate, FormattedDateParts, FormattedDisplayName, FormattedHTMLMessage, FormattedList, FormattedNumber, FormattedNumberParts, FormattedPlural, FormattedRelativeTime, FormattedTime, FormattedTimeParts, IntlProvider, RawIntlProvider, SelectLang } from '/home/code/go-zero-antd-backend/web/src/.umi/plugin-locale';
export { Provider, useModel } from '/home/code/go-zero-antd-backend/web/src/.umi/plugin-model';
export { useRequest, UseRequestProvider, request, getRequestInstance } from '/home/code/go-zero-antd-backend/web/src/.umi/plugin-request';
// plugins types.d.ts
export * from '/home/code/go-zero-antd-backend/web/src/.umi/plugin-access/types.d';
export * from '/home/code/go-zero-antd-backend/web/src/.umi/plugin-layout/types.d';
export * from '/home/code/go-zero-antd-backend/web/src/.umi/plugin-request/types.d';
