// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRole = "role"

// Role mapped from table <role>
type Role struct {
	ID     int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"` // 角色表
	Name   string `gorm:"column:name;not null" json:"name"`                  // 角色名
	Type   int32  `gorm:"column:type;not null;default:1" json:"type"`        // 1.普通用户，2.管理员
	Status int32  `gorm:"column:status;not null;default:1" json:"status"`    // 1.有效，2.无效
	Ctime  int32  `gorm:"column:ctime;not null" json:"ctime"`                // 创建时间
	Utime  int32  `gorm:"column:utime;not null" json:"utime"`                // 更新时间
}

// TableName Role's table name
func (*Role) TableName() string {
	return TableNameRole
}
