// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRolePermissionResource = "role_permission_resource"

// RolePermissionResource mapped from table <role_permission_resource>
type RolePermissionResource struct {
	ID     int64 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"` // 角色和权限资源关联表主键
	RoleID int64 `gorm:"column:role_id;not null" json:"role_id"`            // 角色id
	Prid   int64 `gorm:"column:prid;not null" json:"prid"`                  // 权限资源id
	Status int32 `gorm:"column:status;not null;default:1" json:"status"`    // 1.有效，2.无效
	Ctime  int32 `gorm:"column:ctime;not null" json:"ctime"`                // 创建时间
	Utime  int32 `gorm:"column:utime;not null" json:"utime"`                // 更新时间
}

// TableName RolePermissionResource's table name
func (*RolePermissionResource) TableName() string {
	return TableNameRolePermissionResource
}
