// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID       int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"` // 用户表主键
	Name     string `gorm:"column:name;not null" json:"name"`                  // 用户名
	RoleID   int64  `gorm:"column:role_id;not null" json:"role_id"`            // 角色id
	Password string `gorm:"column:password;not null" json:"password"`          // 密码
	Status   int32  `gorm:"column:status;not null;default:1" json:"status"`    // 是否有效1.有效 2.无效
	Ctime    int32  `gorm:"column:ctime;not null" json:"ctime"`                // 创建时间
	Utime    int32  `gorm:"column:utime;not null" json:"utime"`                // 更新时间
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
