// Code generated by goctl. DO NOT EDIT.
package types

type CodeErrorResponse struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
}

type LoginRequest struct {
	Name     string `form:"name"`
	Password string `form:"password"`
}

type LoginResponse struct {
	Code  int64  `json:"code"`
	Msg   string `json:"msg"`
	Token string `json:"token,optional"`
}

type LoginOutRequest struct {
}

type LoginOutResponse struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
}

type UserInfo struct {
	Id    int64  `json:"id"`
	Name  string `json:"name"`
	Ctime int64  `json:"ctime"`
	Utime int64  `json:"utime"`
}

type EditPasswordRequest struct {
	Password string `json:"password"`
}

type EditPasswordResponse struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
}

type UserInfoRequest struct {
}

type UserInfoResponse struct {
	Code int64    `json:"code"`
	Msg  string   `json:"msg"`
	Data UserInfo `json:"data,optional"`
}

type UserSetRoleRequest struct {
	UserId int64 `form:"user_id"`
	RoleId int64 `form:"role_id"`
}

type UserSetRoleResponse struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
}

type RouterListResquest struct {
}

type Router struct {
	Method string `json:"method"`
	Path   string `json:"path"`
}

type RouterListResponse struct {
	Code int64    `json:"code"`
	Msg  string   `json:"msg"`
	Data []Router `json:"data,optional"`
}

type RouterAddRequest struct {
	Path string `json:"path"`
	Name string `json:"name"`
}

type RouterAddResponse struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
}

type UserAddRequest struct {
	Id       int64  `form:"id"`
	Name     string `form:"name"`
	Password string `form:"password,optional"`
	RoleId   int64  `form:"role_id"`
}

type UserAddResponse struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
}

type User struct {
	Id       int64  `json:"id"`
	Name     string `json:"name"`
	RoleId   int64  `json:"role_id"`
	RoleName string `json:"role_name"`
	Ctime    int64  `json:"ctime"`
	Utime    int64  `json:"utime"`
}

type UserListRequest struct {
	Name string `json:"name,optional"`
}

type UserListResponse struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
	Data []User `json:"data"`
}

type UserDelRequest struct {
	Id int64 `json:"id"`
}

type UserDelResponse struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
}

type RoleListRequest struct {
}

type Role struct {
	Id    int64  `json:"id"`
	Nmae  string `json:"name"`
	Type  int64  `json:"type"`
	Ctime int64  `json:"ctime"`
	Utime int64  `json:"utime"`
}

type RoleListResponse struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
	Data []Role `json:"data,optional"`
}

type RoleEditRequest struct {
	Id   int64  `form:"id"`
	Name string `form:"name"`
	Type int64  `form:"type"`
}

type RoleEditResponse struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
}

type RoleDeleteRequest struct {
	Id int64 `form:"id"`
}

type RoleDeleteResponse struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
}

type PermissionResourceListRequest struct {
}

type PermissionResource struct {
	Name  string `form:"name"`
	Url   string `form:"url"`
	Ctime int64  `form:"ctime"`
}

type PermissionResourceListResponse struct {
	Code int64                `json:"code"`
	Msg  string               `json:"msg"`
	Data []PermissionResource `json:"data"`
}

type PermissionResourceEditRequest struct {
	Id   int64  `form:"id"`
	Name string `form:"name"`
	Url  string `form:"url"`
}

type PermissionResourceEditResponse struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
}

type PermissionResourceDeleteRequest struct {
	Id int64 `form:"id"`
}

type PermissionResourceDeleteResponse struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
}

type RolePermissionResourceListRequest struct {
	RoleId int64 `form:"role_id"`
}

type RolePermissionResource struct {
	Id    int64  `json:"id"`
	Name  string `json:"name"`
	URL   string `json:"url"`
	Ctime int64  `json:"ctime"`
}

type RolePermissionResourceListResponse struct {
	Code        int64                    `json:"code"`
	Msg         string                   `json:"msg"`
	Data        []RolePermissionResource `json:"data"`
	CheckedData []RolePermissionResource `json:"checkdata"`
}

type RolePermissionResourceEditRequest struct {
	RoleId int64  `form:"role_id"`
	Data   string `form:"data"`
}

type RolePermissionResourceEditResponse struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
}
